#!/usr/bin/env python3
"""Export the API documentation as a self-contained bundle.

Produces, in the output directory:

* ``openapi.json``  - the OpenAPI schema generated by the application
* ``swagger.html``  - Swagger UI with the schema and every asset inlined
* ``redoc.html``    - ReDoc with the schema and every asset inlined
* ``wi-lab-api-docs-<version>.zip`` - the three files above

The HTML files need no network access and no running server. The schema is generated by
building the real FastAPI app, with the hardware checks skipped (nothing is started and no
interface is touched), from ``config.example.yaml``.

The Swagger UI / ReDoc bundles are downloaded once at build time from a pinned version.
Usage: python scripts/export_api_docs.py [--out DIR]
"""

import argparse
import json
import os
import re
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Pinned so a release always contains the same renderer it was tested with.
SWAGGER_UI_VERSION = "5.17.14"
REDOC_VERSION = "2.1.5"
SWAGGER_JS_URL = f"https://cdn.jsdelivr.net/npm/swagger-ui-dist@{SWAGGER_UI_VERSION}/swagger-ui-bundle.js"
SWAGGER_CSS_URL = f"https://cdn.jsdelivr.net/npm/swagger-ui-dist@{SWAGGER_UI_VERSION}/swagger-ui.css"
REDOC_JS_URL = f"https://cdn.jsdelivr.net/npm/redoc@{REDOC_VERSION}/bundles/redoc.standalone.js"


def build_schema() -> dict:
    """Generate the OpenAPI schema from the real application, without hardware."""
    os.environ["CONFIG_PATH"] = str(ROOT / "config.example.yaml")
    sys.path.insert(0, str(ROOT))

    # The configuration validator checks that the adapters exist. Generating documentation
    # needs none of that, and must work on a CI runner.
    from wilab.wifi import interface
    interface.validate_interface = lambda iface: None  # type: ignore[assignment]

    from wilab.api import create_app
    return create_app().openapi()


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as resp:  # noqa: S310 - pinned https URL
        return resp.read().decode("utf-8")


def dereference(node: object, root: dict, _stack: tuple = ()) -> object:
    """Return ``node`` with every local ``$ref`` replaced by the schema it points to.

    Swagger UI resolves ``#/components/...`` references relative to the address of the page.
    For a page opened from disk that address is ``file:///.../swagger.html``, which the
    browser refuses to fetch, so every request/response schema fails with "Could not resolve
    reference". Inlining the references removes the lookup altogether. ``openapi.json`` itself
    keeps its references; only the embedded copy is flattened.
    """
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/"):
            if ref in _stack:
                raise ValueError(f"circular reference {ref}; cannot be inlined")
            target: object = root
            for part in ref[2:].split("/"):
                target = target[part.replace("~1", "/").replace("~0", "~")]  # type: ignore[index]
            return dereference(target, root, _stack + (ref,))
        return {k: dereference(v, root, _stack) for k, v in node.items()}
    if isinstance(node, list):
        return [dereference(v, root, _stack) for v in node]
    return node


def js_safe(code: str) -> str:
    """Make a JavaScript bundle safe inside an inline <script> element.

    Only the sequence that would close the element is touched. Escaping every ``</`` would
    also rewrite regular-expression literals such as ``/</g`` and break the bundle.
    """
    return re.sub(r"</(script)", lambda m: "<\\/" + m.group(1), code, flags=re.IGNORECASE)


def json_safe(text: str) -> str:
    """Make JSON safe inside an inline <script>: ``<\\/`` is a valid escape in a JSON string."""
    return text.replace("</", "<\\/")


def css_safe(css: str) -> str:
    if re.search(r"</style", css, re.IGNORECASE):
        raise ValueError("stylesheet contains </style>; cannot be inlined safely")
    return css


def swagger_html(spec_json: str, title: str) -> str:
    sys.path.insert(0, str(ROOT))
    from wilab.api.docs_style import SWAGGER_UI_EXTRA_CSS

    js, css = fetch(SWAGGER_JS_URL), fetch(SWAGGER_CSS_URL)
    css += SWAGGER_UI_EXTRA_CSS
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} - Swagger UI</title>
<style>{css_safe(css)}</style>
</head>
<body>
<div id="swagger-ui"></div>
<script>{js_safe(js)}</script>
<script>
window.onload = function () {{
  window.ui = SwaggerUIBundle({{
    spec: {json_safe(spec_json)},
    dom_id: "#swagger-ui",
    deepLinking: true,
    // Offline documentation: there is no server to call, so "Try it out" is disabled.
    supportedSubmitMethods: [],
    presets: [SwaggerUIBundle.presets.apis],
  }});
}};
</script>
</body>
</html>
"""


def redoc_html(spec_json: str, title: str) -> str:
    js = fetch(REDOC_JS_URL)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} - ReDoc</title>
</head>
<body>
<div id="redoc"></div>
<script>{js_safe(js)}</script>
<script>
Redoc.init({json_safe(spec_json)}, {{}}, document.getElementById("redoc"));
</script>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", default="api-docs", help="output directory (default: api-docs)")
    args = parser.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    schema = build_schema()
    version = schema["info"]["version"]
    title = schema["info"]["title"]
    spec_json = json.dumps(schema, indent=2, ensure_ascii=False)

    files = {
        "openapi.json": spec_json + "\n",
        "swagger.html": swagger_html(
            json.dumps(dereference(schema, schema), ensure_ascii=False), title
        ),
        "redoc.html": redoc_html(json.dumps(schema, ensure_ascii=False), title),
    }
    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")

    archive = out / f"wi-lab-api-docs-{version}.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in files:
            zf.write(out / name, arcname=name)

    print(f"Wi-Lab {version}: wrote {archive} ({archive.stat().st_size // 1024} kB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
